<robot name="my_car_move" xmlns:xacro="http://wiki.ros.org/xacro">

    <xacro:macro name="joint_trans" params="joint_name">
        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${joint_name}_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${joint_name}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${joint_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- drive wheels -->
    <xacro:joint_trans joint_name="left_front_wheel2base_link" />
    <xacro:joint_trans joint_name="right_front_wheel2base_link" />
    <xacro:joint_trans joint_name="left_rear_wheel2base_link" />
    <xacro:joint_trans joint_name="right_rear_wheel2base_link" />
    
    <gazebo>
        <xacro:macro name="my_mecanum_drive_control" params="left_front_wheel right_front_wheel left_rear_wheel right_rear_wheel">
            <plugin name="mecanum_controller" filename="libgazebo_ros_planar_move.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>100.0</updateRate>
                <robotNamespace>/</robotNamespace>
                <leftFrontJoint>${left_front_wheel}</leftFrontJoint>
                <rightFrontJoint>${right_front_wheel}</rightFrontJoint>
                <leftRearJoint>${left_rear_wheel}</leftRearJoint>
                <rightRearJoint>${right_rear_wheel}</rightRearJoint>
                <wheelSeparation>${base_link_long}</wheelSeparation>
                <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
                <torque>2</torque>
                <commandTopic>cmd_vel</commandTopic>
                <odometryTopic>odom</odometryTopic>
                <odometryFrame>odom</odometryFrame>
                <robotBaseFrame>base_footprint</robotBaseFrame>
                <broadcastTF>1</broadcastTF>
            </plugin>
        </xacro:macro>
        
        <xacro:my_mecanum_drive_control left_front_wheel="left_front_wheel2base_link" right_front_wheel="right_front_wheel2base_link"
         left_rear_wheel="left_rear_wheel2base_link" right_rear_wheel="right_rear_wheel2base_link"/>
    </gazebo>

</robot>
