<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- This file contains the common properties and parameters for the robot model. -->

    <!-- Constants -->
    <xacro:property name="PI" value="3.1415926535897931" />

    <!-- Base Properties -->
    <xacro:property name="base_link_long" value="0.25" />
    <xacro:property name="base_link_length" value="0.04" />
    <xacro:property name="base_link_m" value="0.30" />
    <xacro:property name="earth_space" value="0.015" /> 

    <!-- Wheel Properties -->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.035" />
    <xacro:property name="wheel_m" value="0.05" />

    <!-- Camera Properties -->
    <xacro:property name="camera_length" value="0.01" />
    <xacro:property name="camera_width" value="0.025" /> 
    <xacro:property name="camera_height" value="0.025" /> 
    <xacro:property name="camera_m" value="0.01" /> 
    <!-- Camera Position -->
    <xacro:property name="camera_x" value="${base_link_long / 2 + camera_length / 2}" /> 
    <xacro:property name="camera_y" value="0.0" /> 
    <xacro:property name="camera_z" value="${base_link_length / 2 + camera_height / 2}" />

    <!-- Laser and its Support Properties -->
    <!-- Support -->
    <xacro:property name="support_length" value="0.05" /> 
    <xacro:property name="support_radius" value="0.01" /> 
    <xacro:property name="support_m" value="0.02" /> 
    <!-- Support Position -->
    <xacro:property name="support_x" value="0.0" /> 
    <xacro:property name="support_y" value="0.0" /> 
    <xacro:property name="support_z" value="${base_link_length / 2 + support_length / 2}" />
    <!-- Laser -->
    <xacro:property name="laser_length" value="0.05" /> 
    <xacro:property name="laser_radius" value="0.03" /> 
    <xacro:property name="laser_m" value="0.1" />
    <!-- Laser Position -->
    <xacro:property name="laser_x" value="0.0" /> 
    <xacro:property name="laser_y" value="0.0" />
    <xacro:property name="laser_z" value="${support_length / 2 + laser_length / 2}" /> 

</robot> 