global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  transform_tolerance: 0.5

  update_frequency: 10.0
  publish_frequency: 10.0

  plugins:
    - {name: static_layer,    type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  obstacle_layer:
    observation_sources: scan point_cloud
    scan: {
      data_type: LaserScan,
      topic: /scan,
      sensor_frame: laser_frame,
      marking: true,
      clearing: true
    }
    point_cloud: {
      data_type: PointCloud2,
      topic: /camera/depth/points_processed,
      sensor_frame: camera_depth_frame,
      marking: true,
      clearing: true,
      min_obstacle_height: 0.0,
      max_obstacle_height: 2.0,
      observation_persistence: 0.0,
      expected_update_rate: 0.5,
      filter_ground: false
    }
